# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clewie_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatorweb',
            name='url',
            field=models.CharField(default='url', max_length=255),
            preserve_default=False,
        ),
    ]
