# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clewie_web', '0002_estimatorweb_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatorSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_id', models.CharField(max_length=36)),
                ('serialized', models.TextField()),
            ],
        ),
    ]
